[package]
name = "quarb-model"
description = "Model files: derived arbor structure over any Quarb source"
keywords = ["query", "model", "graph", "quarb"]
categories = ["database", "data-structures"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
quarb = { path = "../quarb", version = "0.28.0" }

[dev-dependencies]
quarb-sqlite = { path = "../quarb-sqlite" }
rusqlite = { workspace = true }
