[package]
name = "quarb-arangodb"
description = "ArangoDB adapter for the Quarb query engine"
keywords = ["query", "arangodb", "graph", "quarb", "aql"]
categories = ["api-bindings", "database"]
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
quarb = { path = "../quarb", version = "0.14.0" }
serde_json.workspace = true
thiserror.workspace = true
ureq.workspace = true
